ARG version=14.17.1-alpine
FROM node:${version}

ENV NODE_ENV development
WORKDIR /usr/src/app

#shit to satisfy node-gyp
RUN apk add gcc g++ make python
RUN apk add --update alpine-sdk

COPY ./package*.json .
RUN [ "npm" , "ci" ]
COPY . /usr/src/app
EXPOSE 3000
CMD [ "npm" , "run" , "dev" ]