ARG version=14.17.1-alpine
FROM node:${version}

ENV NODE_ENV development

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json /usr/src/app
RUN [ "npm" , "ci" ]
COPY . /usr/src/app
EXPOSE 3000
CMD [ "npm" , "run" , "dev" ]