version: "3.9"

volumes:
  webpage-db-data:
  client-images:
  static-client:
  letsencrypt:

networks:
  backend-network:
    driver: bridge

services:
  page-db:
    container_name: personal_web_page_dev_db
    image: mongo:latest
    restart: always
    volumes:
      - webpage-db-data:/data/db
    networks:
      - backend-network

  page-server:
    container_name: personal_webpage_dev_server
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      EXPOSED_PORT: ${EXPOSED_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_CONN_STRING: ${DB_CONN_STRING}
      DB_NAME: ${DB_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      API_BASE_URL: ${API_BASE_URL}
    image: chmaikos/devops_hua:latest
    volumes:
      - client-images:/usr/src/app/build/client/images
      - static-client:/usr/src/app/build/client  # Map static files to shared volume
    depends_on:
      - page-db
    networks:
      - backend-network

  web-server:
    image: staticfloat/nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${MY_EMAIL}
      - CERTBOT_DOMAIN=${MY_DOMAIN}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - static-client:/usr/share/nginx/html:ro
    depends_on:
      - page-server
    networks:
      - backend-network
