version: "3.9"

volumes:
  webpage-db-data:

networks:
  backend-network:
    driver: bridge

services:
  page-db:
    container_name: personal_web_page_dev_db
    image: mongo:latest
    restart: always
    volumes:
      - webpage-db-data:/data/db
    networks:
      - backend-network

  page-server:
    container_name: personal_webpage_dev_server
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      EXPOSED_PORT: ${EXPOSED_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_CONN_STRING: ${DB_CONN_STRING}
      DB_NAME: ${DB_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
    build:
      context: .. #Very important it refers where the root will be for the build.
      dockerfile: docker/dockerfiles/Dockerfile.prod
    depends_on:
      - page-db
    networks:
      - backend-network
