version: "3.9"

volumes:
  webpage-db-data:
  static-client:
  nginx_secrets:

networks:
  backend-network:
    driver: bridge

services:
  page-db:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - webpage-db-data:/data/db
    networks:
      - backend-network

  page-server:
    container_name: backend
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      EXPOSED_PORT: ${EXPOSED_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_CONN_STRING: ${DB_CONN_STRING}
      DB_NAME: ${DB_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      API_BASE_URL: ${API_BASE_URL}
    image: chmaikos/devops_hua:latest
    volumes:
      - static-client:/usr/src/app/build/client
    depends_on:
      - page-db
    networks:
      - backend-network

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${MY_EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-client:/usr/src/app/build/client
      - nginx_secrets:/etc/letsencrypt
      - ../nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - page-server
    networks:
      - backend-network
