version: "3.9"

volumes:
  webpage-db-data:
  client-images:

networks:
  backend-network:
    driver: bridge

services:
  page-db:
    container_name: personal_web_page_dev_db
    image: mongo:latest
    restart: always
    volumes:
      - webpage-db-data:/data/db
    networks:
      - backend-network

  page-server:
    container_name: personal_webpage_dev_server
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET:-123}
      - NODE_ENV=${NODE_ENV:-production}
    image: chmaikos/devops_hua:latest 
    ports:
      - "${EXPOSED_PORT:-80}:${PORT:-80}"
    volumes:
      - client-images:/usr/src/app/build/client/images
    depends_on:
      - page-db
    networks:
      - backend-network
