version: "3.9"

volumes:
  webpage-db-data:
  client-images:
  static-client:

networks:
  backend-network:
    driver: bridge

services:
  page-db:
    container_name: personal_web_page_dev_db
    image: mongo:latest
    restart: always
    volumes:
      - webpage-db-data:/data/db
    networks:
      - backend-network

  page-server:
    container_name: personal_webpage_dev_server
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      EXPOSED_PORT: ${EXPOSED_PORT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_CONN_STRING: ${DB_CONN_STRING}
      DB_NAME: ${DB_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
    build:
      context: .. #Very important it refers where the root will be for the build.
      dockerfile: docker/dockerfiles/Dockerfile.prod
    volumes:
      - client-images:/usr/src/app/build/client/images
      - static-client:/usr/src/app/build/client  # Map static files to shared volume
    depends_on:
      - page-db
    networks:
      - backend-network

  nginx:
    container_name: personal_webpage_nginx
    image: nginx:latest
    volumes:
      - ../nginx/nginx_docker.conf:/etc/nginx/nginx.conf
      - static-client:/etc/html/www/static/client  # Map shared volume to Nginx path
    ports:
      - "80:80"  # Expose port 80 to the world
    depends_on:
      - page-server
    networks:
      - backend-network
