apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: page-server-ingress
  namespace: devops  # Make sure this is set correctly
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
  - host: devops.red-net.gr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: page-server
            port:
              number: 80
